# Generated by Django 4.0.10 on 2023-09-10 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalizables', '0003_designedpersonalizablevariant_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='designed_personalizable',
        ),
        migrations.AddField(
            model_name='product',
            name='designed_personalizable_variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='personalizables.designedpersonalizablevariant'),
            preserve_default=False,
        ),
    ]
