# Generated by Django 4.0.10 on 2023-09-10 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0002_remove_product_designed_personalizable_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='designed_personalizable_variant',
        ),
        migrations.AddField(
            model_name='product',
            name='content_type',
            field=models.ForeignKey(default=None, limit_choices_to={'model__in': ['design', 'designedpersonalizablevariant']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='object_id',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_origin',
            field=models.CharField(choices=[('For Self', 'For Self'), ('For Store', 'For Store')], default='For Self', max_length=255),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
