# Generated by Django 5.0 on 2024-02-18 22:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("personalizables", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product_origin",
                    models.CharField(
                        choices=[("For Self", "For Self"), ("For Store", "For Store")],
                        default="For Self",
                        max_length=255,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("personalizable", "Personalizable"),
                            ("design", "Design"),
                        ],
                        default="personalizable",
                        max_length=255,
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personalizables.category",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": ["design", "designedpersonalizablevariant"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
