# Generated by Django 5.0 on 2024-07-18 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0001_initial"),
        ("personalizables", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountpromotion",
            name="design",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="designs.design",
            ),
        ),
        migrations.AddField(
            model_name="discountpromotion",
            name="personalizable_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="personalizables.personalizablevariant",
            ),
        ),
        migrations.AddField(
            model_name="discountpromotion",
            name="product_variant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productvariant",
            ),
            preserve_default=False,
        ),
    ]
