# Generated by Django 5.0 on 2024-05-17 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_permission_role_permissions"),
        ("organizations", "0002_alter_organizationmembership_role"),
        ("personalizables", "0003_department_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariantPreview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_path", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "product_variant_previews",
            },
        ),
        migrations.RenameModel(
            old_name="ProductReview",
            new_name="ProductVariantReview",
        ),
        migrations.DeleteModel(
            name="CodePromotion",
        ),
        migrations.RemoveField(
            model_name="productpreview",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="personalization_method",
        ),
        migrations.RemoveField(
            model_name="product",
            name="self_made",
        ),
        migrations.RemoveField(
            model_name="productvariantreview",
            name="account",
        ),
        migrations.RemoveField(
            model_name="productvariantreview",
            name="product",
        ),
        migrations.AddField(
            model_name="amountpromotion",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bulkpurchasepromotion",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="discountpromotion",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="firsttimepurchasepromotion",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="firsttimepurchasepromotion",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="flashsalepromotion",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="freeshippingpromotion",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loyaltypromotion",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="membersonlypromotion",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="editable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="accounts.accountprofile",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="category",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="designed_personalizable_variant",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="personalizables.designedpersonalizablevariant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productvariants",
                to="products.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productvariantreview",
            name="account_profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.accountprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariantreview",
            name="product_variant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productreview",
                to="products.productvariant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="referralpromotion",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="firsttimepurchasepromotion",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterModelTable(
            name="productvariant",
            table="product_variants",
        ),
        migrations.AddField(
            model_name="productvariantpreview",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productvariantpreviews",
                to="products.product",
            ),
        ),
        migrations.DeleteModel(
            name="ProductDiscountPromotion",
        ),
        migrations.DeleteModel(
            name="ProductPreview",
        ),
    ]
