# Generated by Django 5.0 on 2024-05-20 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="personalizables.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="personalizables.department",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="self_made",
            field=models.BooleanField(default=False),
        ),
    ]
