# Generated by Django 5.0 on 2024-07-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="amountpromotion",
            old_name="code",
            new_name="promotion_identification_code",
        ),
        migrations.RenameField(
            model_name="bulkpurchasepromotion",
            old_name="code",
            new_name="promotion_identification_code",
        ),
        migrations.RenameField(
            model_name="discountpromotion",
            old_name="code",
            new_name="promotion_identification_code",
        ),
        migrations.RenameField(
            model_name="firsttimepurchasepromotion",
            old_name="code",
            new_name="promotion_identification_code",
        ),
        migrations.RenameField(
            model_name="flashsalepromotion",
            old_name="code",
            new_name="promotion_identification_code",
        ),
        migrations.RenameField(
            model_name="freeshippingpromotion",
            old_name="code",
            new_name="promotion_identification_code",
        ),
        migrations.RenameField(
            model_name="loyaltypromotion",
            old_name="code",
            new_name="promotion_identification_code",
        ),
        migrations.RenameField(
            model_name="membersonlypromotion",
            old_name="code",
            new_name="promotion_identification_code",
        ),
        migrations.RenameField(
            model_name="referralpromotion",
            old_name="code",
            new_name="promotion_identification_code",
        ),
        migrations.AddField(
            model_name="amountpromotion",
            name="redeem_codes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bulkpurchasepromotion",
            name="redeem_codes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discountpromotion",
            name="redeem_codes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="firsttimepurchasepromotion",
            name="redeem_codes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flashsalepromotion",
            name="redeem_codes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="freeshippingpromotion",
            name="redeem_codes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loyaltypromotion",
            name="redeem_codes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membersonlypromotion",
            name="redeem_codes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="referralpromotion",
            name="redeem_codes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
