# Generated by Django 5.0 on 2024-03-07 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0001_initial"),
        ("products", "0002_productpreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdesignedpersonalizablevariant",
            name="designed_personalizable_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productdesignedpersonalizablevariant",
                to="personalizables.designedpersonalizablevariant",
            ),
        ),
    ]
