# Generated by Django 5.0 on 2024-07-19 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_discountpromotion_design_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariantpreview",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productvariantpreviews",
                to="products.productvariant",
            ),
        ),
    ]
