# Generated by Django 5.0 on 2024-07-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0002_rename_code_amountpromotion_promotion_identification_code_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="product",
            name="starting_price",
        ),
        migrations.AddField(
            model_name="product",
            name="latest_publication_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
