# Generated by Django 5.0 on 2024-07-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_productvariantpreview_product_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
