# Generated by Django 5.0 on 2024-03-07 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0001_initial"),
        (
            "products",
            "0003_alter_productdesignedpersonalizablevariant_designed_personalizable_variant",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdesignedpersonalizablevariant",
            name="designed_personalizable_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="personalizables.designedpersonalizablevariant",
            ),
        ),
        migrations.AlterField(
            model_name="productdesignedpersonalizablevariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productdesignedpersonalizablevariant",
                to="products.product",
            ),
        ),
    ]
