# Generated by Django 5.0 on 2024-07-19 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariantreview",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productvariantreviews",
                to="products.productvariant",
            ),
        ),
    ]
