# Generated by Django 5.0 on 2024-03-09 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        ("products", "0005_bulkpurchasepromotion_firsttimepurchasepromotion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="workshop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workshop",
                to="organizations.workshop",
            ),
        ),
        migrations.DeleteModel(
            name="ProductDesignedPersonalizableVariant",
        ),
    ]
