# Generated by Django 5.0 on 2024-07-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_productvariantreview_product_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_sponsored",
            field=models.BooleanField(default=False),
        ),
    ]
