# Generated by Django 5.0 on 2024-03-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_product_workshop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="to_be_published",
            field=models.BooleanField(default=False),
        ),
    ]
