# Generated by Django 5.0 on 2024-07-21 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "personalizables",
            "0004_alter_designedpersonalizablezone_designed_personalizable_variant",
        ),
        ("products", "0006_product_is_sponsored"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="personalization_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="personalizables.personalizationmethod",
            ),
        ),
    ]
