# Generated by Django 5.0 on 2024-07-21 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("products", "0007_product_personalization_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariantreview",
            name="account_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accountprofilereviews",
                to="accounts.accountprofile",
            ),
        ),
    ]
