# Generated by Django 5.0 on 2024-03-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_product_to_be_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="starting_price",
        ),
    ]
