# Generated by Django 5.0 on 2024-07-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_productvariantreview_account_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="self_made",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="to_be_published",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
