# Generated by Django 5.0 on 2024-07-15 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("empty", "Empty"),
                            ("partially_filled", "Partially Filled"),
                            ("full", "Full"),
                        ],
                        default="empty",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "inventories",
            },
        ),
        migrations.CreateModel(
            name="BusinessOwnerProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("full_address", models.TextField(max_length=255)),
                ("identification_number", models.CharField(max_length=100)),
                ("biography", models.TextField(null=True)),
                (
                    "contact_email",
                    models.EmailField(max_length=254, null=True, unique=True),
                ),
                ("contact_phone", models.CharField(max_length=30, null=True)),
                (
                    "account_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_owner_profile",
                        to="accounts.accountprofile",
                    ),
                ),
            ],
            options={
                "db_table": "business_owner_profiles",
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sku", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.IntegerField()),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("alert_threshold", models.IntegerField(default=10)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.inventory",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_items",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(max_length=100)),
                ("legal_name", models.CharField(max_length=100)),
                ("description", models.TextField(null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("tax_number", models.CharField(max_length=100, null=True)),
                ("registration_number", models.CharField(max_length=100, null=True)),
                ("registratioin_date", models.DateField(null=True)),
                ("registration_country", models.CharField(max_length=100, null=True)),
                (
                    "registration_certificate_path",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "organization_contact_email",
                    models.EmailField(max_length=254, null=True, unique=True),
                ),
                (
                    "organization_contact_phone",
                    models.CharField(max_length=30, null=True),
                ),
                (
                    "business_owner_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.businessownerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "organizations",
            },
        ),
        migrations.CreateModel(
            name="OrganizationProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("logo_path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "banner_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_sponsored", models.BooleanField(default=False)),
                ("head_office_address", models.TextField(max_length=255)),
                ("social_media_links", models.JSONField(blank=True, null=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orgprofile",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_profiles",
            },
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_sponsored", models.BooleanField(default=False)),
                ("description", models.TextField(max_length=255, null=True)),
                ("address", models.TextField(max_length=255, null=True)),
                (
                    "contact_email",
                    models.EmailField(max_length=254, null=True, unique=True),
                ),
                ("contact_phone", models.CharField(max_length=25, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "workshops",
            },
        ),
        migrations.AddField(
            model_name="inventory",
            name="workshop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="organizations.workshop"
            ),
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active_membership", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "db_table": "organization_memberships",
                "unique_together": {("organization", "account")},
            },
        ),
        migrations.CreateModel(
            name="WorkshopMembership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active_membership", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.role",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.workshop",
                    ),
                ),
            ],
            options={
                "db_table": "workshop_memberships",
                "unique_together": {("workshop", "account")},
            },
        ),
    ]
