# Generated by Django 5.0 on 2024-06-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationprofile",
            name="facebook_link",
        ),
        migrations.RemoveField(
            model_name="organizationprofile",
            name="instagram_link",
        ),
        migrations.RemoveField(
            model_name="organizationprofile",
            name="linkedin_link",
        ),
        migrations.RemoveField(
            model_name="organizationprofile",
            name="x_link",
        ),
        migrations.RemoveField(
            model_name="organizationprofile",
            name="youtube_link",
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="social_media_links",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
