# Generated by Django 5.0 on 2024-02-28 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="inventory",
            table="inventories",
        ),
        migrations.AlterModelTable(
            name="inventoryitem",
            table="inventory_items",
        ),
        migrations.AlterModelTable(
            name="organization",
            table="organizations",
        ),
        migrations.AlterModelTable(
            name="organizationmembership",
            table="organization_memberships",
        ),
        migrations.AlterModelTable(
            name="organizationprofile",
            table="organization_profiles",
        ),
        migrations.AlterModelTable(
            name="workshop",
            table="workshops",
        ),
    ]
