# Generated by Django 5.0 on 2024-02-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="9258c2cc-ba1c-4758-b5d8-c68be7c7adea",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="965cea18-b748-4dff-ae24-f960f9f6f3aa",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="99684bfa-2ec9-46ac-8cf3-49b5ac6074aa",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="3f7dc384-ee90-446f-9e36-77b987094367",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organizationprofile",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="0dcb358e-847f-43a3-805a-2ba0bee55ff5",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="eea96d9b-26ae-4cd9-a534-008f7297c5a4",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
