# Generated by Django 5.0 on 2024-02-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_alter_inventory_id_alter_inventoryitem_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="d9f0c265-097e-481c-bf6c-2a82a18be9d8",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="572585ac-12e4-4376-86fd-020f0a4e1214",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="f2fad813-2810-482e-9d7f-8da2f132389c",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="0ebc40f7-754a-4fe6-b319-bfeabfe8cb7a",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organizationprofile",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="0840a870-ffe7-4487-9350-3f1cd94aa644",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="27f070b7-d895-4670-be43-5a08d22b42ab",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
