# Generated by Django 5.0 on 2024-06-22 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_default_delivery_address_deliveryaddress_is_default"),
        ("organizations", "0002_remove_organizationprofile_facebook_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="name",
            new_name="business_name",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="contact_email",
            new_name="organization_contact_email",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="contact_phone",
            new_name="organization_contact_phone",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="commerce_registry_number",
            new_name="registration_country",
        ),
        migrations.RenameField(
            model_name="organizationmembership",
            old_name="is_active",
            new_name="is_active_membership",
        ),
        migrations.RenameField(
            model_name="workshop",
            old_name="email",
            new_name="contact_email",
        ),
        migrations.RenameField(
            model_name="workshop",
            old_name="phone",
            new_name="contact_phone",
        ),
        migrations.RenameField(
            model_name="workshopmembership",
            old_name="is_active",
            new_name="is_active_membership",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="address",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="organizationprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="workshopmembership",
            name="organization_membership",
        ),
        migrations.AddField(
            model_name="inventory",
            name="status",
            field=models.CharField(
                choices=[
                    ("empty", "Empty"),
                    ("partially_filled", "Partially Filled"),
                    ("full", "Full"),
                ],
                default="empty",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="sku",
            field=models.CharField(default=None, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="legal_name",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="registratioin_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="registration_certificate_path",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="registration_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="tax_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="head_office_address",
            field=models.TextField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workshop",
            name="address",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="description",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="workshopmembership",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.role",
            ),
        ),
    ]
