# Generated by Django 5.0 on 2024-02-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations",
            "0002_alter_inventory_table_alter_inventoryitem_table_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="commerce_registry_number",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
