# Generated by Django 5.0 on 2024-02-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_alter_inventory_id_alter_inventoryitem_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="6a5bf1fb-f270-4936-8ac2-04a28e60839c",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="bcd9d8db-ed00-4c3a-8c26-096a52310f16",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="67a5b973-42b0-44f2-813c-675372bd07e7",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="26d5472f-5080-4feb-a11a-d5fc83d6435b",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organizationprofile",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="b1c2e2ff-980c-469b-bb32-603d8ec79128",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="id",
            field=models.AutoField(
                db_index=True,
                default="298f7922-7f99-4323-90c2-2732fa779825",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
