# Generated by Django 5.0 on 2024-02-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_organization_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="contact_email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="contact_phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
