# Generated by Django 5.0 on 2024-02-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_alter_inventory_id_alter_inventoryitem_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="5781e172-18d1-4c4a-a9af-de6f06ddc975",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="9e4fc5f2-f435-4681-b5ef-1911438d0cd4",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="c54994e6-a297-4b0d-b2c3-207fcdd584bb",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="47c29be3-0402-40c8-b971-8ba42ee36cc0",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organizationprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="9b592932-7f74-427c-a21c-179cb3c0e8e0",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="1ea07d00-2ee2-4b52-89df-9c054d838f8b",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
