# Generated by Django 5.0 on 2024-06-24 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_default_delivery_address_deliveryaddress_is_default"),
        ("organizations", "0004_organization_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="account",
        ),
        migrations.AddField(
            model_name="organization",
            name="account_profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.accountprofile",
            ),
            preserve_default=False,
        ),
    ]
