# Generated by Django 5.0 on 2024-06-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_remove_organization_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="organization_contact_phone",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
