# Generated by Django 5.0 on 2024-02-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_alter_organization_contact_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationprofile",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="organizationprofile",
            name="website",
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="logo_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
