# Generated by Django 5.0 on 2024-02-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_remove_organizationprofile_logo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="organizationprofile",
            name="social_media_links",
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="banner_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="facebook_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="instagram_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="linkedin_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="x_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="youtube_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
