# Generated by Django 5.0 on 2024-06-29 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0006_rename_permission_description_permission_description_and_more",
        ),
        ("organizations", "0006_alter_organization_organization_contact_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="account_profile",
        ),
        migrations.CreateModel(
            name="BusinessOwnerProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("full_address", models.TextField(max_length=255)),
                ("identification_number", models.CharField(max_length=100)),
                ("biography", models.TextField(null=True)),
                (
                    "contact_email",
                    models.EmailField(max_length=254, null=True, unique=True),
                ),
                ("contact_phone", models.CharField(max_length=30, null=True)),
                (
                    "account_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_owner_profile",
                        to="accounts.accountprofile",
                    ),
                ),
            ],
            options={
                "db_table": "business_owner_profiles",
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="business_owner_profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.businessownerprofile",
            ),
            preserve_default=False,
        ),
    ]
