# Generated by Django 5.0 on 2024-02-29 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_remove_organizationprofile_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationprofile",
            name="phone_number",
        ),
    ]
