# Generated by Django 5.0 on 2024-07-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_remove_organization_account_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="is_sponsored",
            field=models.BooleanField(default=False),
        ),
    ]
