# Generated by Django 5.0 on 2024-03-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_remove_organizationprofile_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workshop",
            old_name="location",
            new_name="address",
        ),
        migrations.AddField(
            model_name="workshop",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
