# Generated by Django 5.0 on 2024-03-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations",
            "0009_rename_location_workshop_address_workshop_phone_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="phone",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
