# Generated by Django 5.0 on 2024-03-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0010_alter_workshop_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="location",
        ),
        migrations.AddField(
            model_name="inventory",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
