# Generated by Django 5.0 on 2024-03-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0011_remove_inventory_location_inventory_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "United States Dollar"),
                    ("EUR", "Euro"),
                    ("DA", "Algerian Dinar"),
                ],
                default="DA",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
