# Generated by Django 5.0 on 2024-03-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0012_inventoryitem_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationprofile",
            name="sponsored",
            field=models.BooleanField(default=False),
        ),
    ]
