# Generated by Django 5.0 on 2024-03-06 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0014_alter_organizationprofile_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationprofile",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orgprofile",
                to="organizations.organization",
            ),
        ),
    ]
