# Generated by Django 5.0 on 2024-03-06 22:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0015_alter_organizationprofile_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationprofile",
            name="sponsored",
        ),
    ]
