# Generated by Django 5.0 on 2024-02-26 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_account_id_alter_accountprofile_id"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryMethod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("delivery_time", models.DurationField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="order",
            old_name="user_profile",
            new_name="account_profile",
        ),
        migrations.AddField(
            model_name="bill",
            name="billing_address",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.deliveryaddress",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bill",
            name="order",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bill",
            name="payment_method",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.paymentmethod",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bill",
            name="payment_status",
            field=models.CharField(
                choices=[("Paid", "Paid"), ("Unpaid", "Unpaid")],
                default="Unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(
                choices=[("DA", "DA"), ("EUR", "EUR"), ("USD", "USD")],
                default="DA",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Confirmed", "Confirmed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("delivery_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Shipped", "Shipped"),
                            ("Delivered", "Delivered"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.deliveryaddress",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
                (
                    "delivery_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.deliverymethod",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
