# Generated by Django 5.0 on 2024-02-27 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-order_date"]},
        ),
        migrations.AlterModelTable(
            name="bill",
            table="bills",
        ),
        migrations.AlterModelTable(
            name="order",
            table="orders",
        ),
        migrations.AlterModelTable(
            name="orderitem",
            table="order_items",
        ),
    ]
