# Generated by Django 5.0 on 2024-05-20 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_variant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderitem",
                to="products.productvariant",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items_of_a_product",
                to="products.productvariant",
            ),
        ),
    ]
