# Generated by Django 5.0 on 2024-03-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items_of_a_product",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accounts.deliveryaddress",
            ),
        ),
        migrations.AddField(
            model_name="deliveryitem",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.delivery"
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="orders.deliverymethod",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="account_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_of_an_account",
                to="accounts.accountprofile",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accounts.deliveryaddress",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accounts.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="bill_of_an_order",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderitem",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderitem",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="deliveryitem",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="orders.orderitem"
            ),
        ),
    ]
