# Generated by Django 5.0 on 2024-02-27 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_options_alter_bill_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="delivery",
            table="deliveries",
        ),
        migrations.AlterModelTable(
            name="deliveryitem",
            table="delivery_items",
        ),
        migrations.AlterModelTable(
            name="deliverymethod",
            table="delivery_methods",
        ),
    ]
