# Generated by Django 5.0 on 2024-02-26 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_account_id_alter_accountprofile_id"),
        ("orders", "0002_alter_order_delivery_address_alter_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="account_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_of_an_account",
                to="accounts.accountprofile",
            ),
        ),
    ]
