# Generated by Django 5.0 on 2024-07-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_rename_product_cartitem_product_variant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="open",
        ),
        migrations.AddField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[("Open", "open"), ("Closed", "closed")],
                default="Open",
                max_length=20,
            ),
        ),
    ]
