# Generated by Django 5.0 on 2024-02-27 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_delivery_table_alter_deliveryitem_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cart",
            table="carts",
        ),
        migrations.AlterModelTable(
            name="cartitem",
            table="cart_items",
        ),
    ]
