# Generated by Django 5.0 on 2024-02-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_cart_table_alter_cartitem_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverymethod",
            name="delivery_time",
            field=models.CharField(),
        ),
    ]
