# Generated by Django 5.0 on 2024-02-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="cfdb7b99-809a-4d2a-98b4-59ee1cc3c504",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="51d5f7aa-f84c-4542-a604-9a3f88684f85",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
