# Generated by Django 5.0 on 2024-02-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="5d676d74-db7a-409c-bf76-3acc3fafd136",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="f230af64-1642-4ac8-988b-0b3631b68bcf",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
