# Generated by Django 5.0 on 2024-02-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="fc32b040-2ff5-498e-9f76-93125ef61c1c",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="b02ee1b0-2331-49d9-a33b-3304ae4b25b5",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
