# Generated by Django 5.0 on 2024-02-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="active",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="admin",
            new_name="is_admin",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="staff",
            new_name="is_staff",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="superuser",
            new_name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="account",
            name="username",
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
