# Generated by Django 5.0 on 2024-02-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="177a2bbd-f62e-4fd0-b523-f81bfa8ca22c",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterModelTable(
            name="accountblacklist",
            table="blacklist_account",
        ),
    ]
