# Generated by Django 5.0 on 2024-05-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Published"),
                    ("not specified", "Not Specified"),
                ],
                default="not specified",
                max_length=15,
                null=True,
            ),
        ),
    ]
