# Generated by Django 5.0 on 2024-06-03 20:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountprofile",
            old_name="user_name",
            new_name="username",
        ),
    ]
