# Generated by Django 5.0 on 2024-06-03 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountprofile",
            name="age",
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="social_media_links",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="user_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="default_delivery_address",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="accountblacklist",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="actiontoken",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 4, 12, 10, 40, 253030, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
