# Generated by Django 5.0 on 2024-07-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="personili_gems",
            field=models.IntegerField(default=10),
        ),
    ]
