# Generated by Django 5.0 on 2024-02-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="b958129d-d40e-40a7-b6f8-8ffd52512a1b",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="ae9e2a9c-1f7f-46b4-8c43-b671fa7a1b55",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
