# Generated by Django 5.0 on 2024-02-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_active_account_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blacklist",
            name="ip_address",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterModelTable(
            name="account",
            table="account",
        ),
        migrations.AlterModelTable(
            name="accountprofile",
            table="account_profile",
        ),
        migrations.AlterModelTable(
            name="blacklist",
            table="blacklist",
        ),
        migrations.AlterModelTable(
            name="deliveryaddress",
            table="delivery_address",
        ),
        migrations.AlterModelTable(
            name="feedback",
            table="feedback",
        ),
        migrations.AlterModelTable(
            name="paymentmethod",
            table="payment_details",
        ),
        migrations.AlterModelTable(
            name="transaction",
            table="transaction",
        ),
        migrations.AlterModelTable(
            name="wallet",
            table="wallet",
        ),
    ]
