# Generated by Django 5.0 on 2024-06-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0002_remove_accountprofile_age_accountprofile_biography_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontoken",
            name="expiry_date",
            field=models.DateTimeField(),
        ),
    ]
