# Generated by Django 5.0 on 2024-02-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="4102e05f-b612-4272-8842-d883dfde5f86",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="2ed85850-8f2b-4e56-8318-0c11c8463a23",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
