# Generated by Django 5.0 on 2024-02-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="0883fe03-fb82-49d0-a2f4-929dff9d4d0e",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Published"),
                    ("not specified", "Not Specified"),
                ],
                default="not specified",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="0a64ed24-232f-41fe-a66f-7cc450663ef8",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
