# Generated by Django 5.0 on 2024-05-29 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_actiontoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontoken",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 31, 0, 25, 28, 653730)
            ),
        ),
        migrations.AlterField(
            model_name="actiontoken",
            name="token",
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
