# Generated by Django 5.0 on 2024-02-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="02525a56-dd58-45c8-bed4-eddfabbb4cb3",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="71ea7738-1622-4df3-a012-ee5dfde27550",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
