# Generated by Django 5.0 on 2024-06-22 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_roleaccount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryaddress",
            old_name="default_delivery_address",
            new_name="is_default",
        ),
    ]
