# Generated by Django 5.0 on 2024-02-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="4be0addb-2720-4ad5-9919-12aa276f40d2",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="a304efe5-830f-4b13-9de4-bc7f07cf631a",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
