# Generated by Django 5.0 on 2024-02-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_account_id_alter_accountprofile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="3f597daf-d541-4ba2-91df-53f037e162e0",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="9bf6cdf0-ed0b-4953-9928-2e2930f08c17",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
