# Generated by Django 5.0 on 2024-02-18 22:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_blacklist_ip_address_alter_account_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(null=True)),
            ],
            options={
                "db_table": "role",
            },
        ),
        migrations.RenameField(
            model_name="accountprofile",
            old_name="username",
            new_name="last_name",
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="e93feaf2-b97c-4578-843a-9f749b16db77",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
