# Generated by Django 5.0 on 2024-02-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="a26d333b-1680-4a4e-9dd2-384a6b34e2ee",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="age",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="f1499bff-a571-4818-89a4-4cd2f888d56c",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
