# Generated by Django 5.0 on 2024-02-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_accountblacklist_role_delete_blacklist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="81ee80a7-9233-44b5-8d3d-297ce2648ae7",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
