# Generated by Django 5.0 on 2024-06-26 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_default_delivery_address_deliveryaddress_is_default"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RolePermission",
        ),
    ]
