# Generated by Django 5.0 on 2024-02-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="e57a660e-fdce-468c-a020-34b9b28357b3",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="bb8bb86f-9f26-4289-bc07-2863ebdeec48",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
