# Generated by Django 5.0 on 2024-05-29 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_actiontoken_expiry_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontoken",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 31, 0, 38, 7, 478312)
            ),
        ),
    ]
