# Generated by Django 5.0 on 2024-02-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_account_id_alter_accountprofile_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="d1bc6ad5-9aca-4adc-9a49-a799fd489256",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="1e4da51e-72a6-42b8-bae6-2e7183489961",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
