# Generated by Django 5.0 on 2024-05-30 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_actiontoken_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontoken",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 31, 13, 37, 52, 731242)
            ),
        ),
        migrations.AlterField(
            model_name="actiontoken",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("email_verification", "EMAIL_VERIFICATION"),
                    ("password_reset", "PASSWORD_RESET"),
                    ("account_suspension", "ACCOUNT_SUSPENSION"),
                ],
                default="email_verification",
                max_length=255,
            ),
        ),
    ]
