# Generated by Django 5.0 on 2024-06-26 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_delete_rolepermission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="permission",
            old_name="permission_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="permission_name",
            new_name="name",
        ),
    ]
