# Generated by Django 5.0 on 2024-02-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="d89cc5b3-8143-4639-bb05-e252e54c84b5",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="e11861b0-60fe-4905-9bde-c0b8092f6f0a",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
