# Generated by Django 5.0 on 2024-02-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="d4cca51f-5e24-456b-ae61-7a6a8231b565",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="651c1006-e5da-44b5-9ca9-cefb1a8f2f83",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
