# Generated by Django 5.0 on 2024-02-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="69554d65-0298-4f58-9f18-627369221510",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="7a3b7dcb-ac07-4cdb-a643-ce653f7c4706",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterModelTable(
            name="account",
            table="accounts",
        ),
        migrations.AlterModelTable(
            name="accountblacklist",
            table="blacklist_accounts",
        ),
        migrations.AlterModelTable(
            name="accountprofile",
            table="account_profiles",
        ),
        migrations.AlterModelTable(
            name="deliveryaddress",
            table="delivery_addresses",
        ),
        migrations.AlterModelTable(
            name="feedback",
            table="feedbacks",
        ),
        migrations.AlterModelTable(
            name="paymentmethod",
            table="payment_methods",
        ),
        migrations.AlterModelTable(
            name="role",
            table="roles",
        ),
        migrations.AlterModelTable(
            name="transaction",
            table="transactions",
        ),
        migrations.AlterModelTable(
            name="wallet",
            table="wallets",
        ),
    ]
