# Generated by Django 5.0 on 2024-06-01 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_actiontoken_expiry_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountblacklist",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="actiontoken",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 2, 21, 33, 31, 863415, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
