# Generated by Django 5.0 on 2024-02-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_account_id_alter_accountprofile_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="bd3d36b7-263a-40ab-9385-9d50fe687343",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="cfafb639-0d31-434d-a60b-a68647c82888",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
