# Generated by Django 5.0 on 2024-06-02 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_accountblacklist_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontoken",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 3, 11, 52, 2, 93481, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
