# Generated by Django 5.0 on 2024-02-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="bb904c51-20df-41ee-83a1-2a50e475655c",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="e66ad64c-cda9-4fad-8e0c-41b2dedc1240",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
