# Generated by Django 5.0 on 2024-02-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="28b957e6-f5f3-4922-a94a-b79254cd5fdd",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="6aa590fe-3e91-485b-8914-e470da9691c8",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
