# Generated by Django 5.0 on 2024-02-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="857eb533-676a-47a2-871c-8a579ac19bbc",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="a5d47040-5e09-405f-81bc-f2a2b7f4881f",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
