# Generated by Django 5.0 on 2024-02-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="131d7723-8bf7-48de-8627-0d8ab8130aec",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="09b744cc-084e-4140-99c6-da8f8911e2ba",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
