# Generated by Django 5.0 on 2024-02-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="8f28e511-01f1-4f79-a3e0-7c4bed05a779",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="5537af7b-0325-4daf-ab67-a15896ed56a8",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
