# Generated by Django 5.0 on 2024-02-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="2e8d51d2-4fed-480f-95c2-859b2574abda",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="18c699af-d828-40b2-81d9-1f0b54bb01d0",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
