# Generated by Django 5.0 on 2024-06-02 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_actiontoken_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontoken",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 3, 17, 34, 7, 812397, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
