# Generated by Django 5.0 on 2024-02-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="530aea98-6ce3-4252-83cb-bd0ca3cfca18",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="bc830c74-e597-4bef-86a5-6c549e38fba1",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
