# Generated by Django 5.0 on 2024-03-01 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryaddress",
            name="account_profile",
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="account",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveryaddress",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
