# Generated by Django 5.0 on 2024-03-04 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_remove_deliveryaddress_account_profile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryaddress",
            name="account",
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="account_profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveryaddress",
                to="accounts.accountprofile",
            ),
            preserve_default=False,
        ),
    ]
