# Generated by Django 5.0 on 2024-02-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="bda0bd83-fc27-4370-887a-bf6d81646524",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="db84018f-54d6-4498-858b-03af040e7653",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
