# Generated by Django 5.0 on 2024-02-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="21234afc-1fc1-4144-82a3-0fef029b5b88",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="c7c134fb-4b6a-4b58-8d92-bbffcb4001fa",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
