# Generated by Django 5.0 on 2024-02-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="a8d896eb-d08a-4ca1-838f-d5ec3d0e83d4",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="e68f5d7e-cf82-431b-adbb-e6d30baffb39",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
