# Generated by Django 5.0 on 2024-02-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_alter_account_id_alter_accountprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default="8a213200-0be1-4017-8c7f-ac8716b80732",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="7fe9b4dc-427d-47a4-af13-f10a4b2d00a2",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
