# Generated by Django 5.0 on 2024-07-15 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "icon_1_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "icon_2_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "icon_3_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "themes",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="My Collection", max_length=255)),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection",
                        to="organizations.workshop",
                    ),
                ),
            ],
            options={
                "db_table": "collections",
            },
        ),
        migrations.CreateModel(
            name="Design",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
                ("tags", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "design_type",
                    models.CharField(
                        choices=[("3d", "3D"), ("2d", "2D")],
                        default="2d",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=255,
                    ),
                ),
                ("to_be_published", models.BooleanField(default=False)),
                (
                    "latest_publication_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("sponsored", models.BooleanField(default=False)),
                ("free_usage", models.BooleanField(default=False)),
                ("exclusive_usage", models.BooleanField(default=False)),
                (
                    "limited_usage_with_same_collection",
                    models.BooleanField(default=False),
                ),
                (
                    "limited_usage_with_same_workshop",
                    models.BooleanField(default=False),
                ),
                (
                    "limited_usage_with_same_organization",
                    models.BooleanField(default=False),
                ),
                (
                    "limited_usage_with_designer_uploads",
                    models.BooleanField(default=False),
                ),
                ("limited_usage_with_user_uploads", models.BooleanField(default=False)),
                (
                    "limited_usage_with_other_workshops",
                    models.BooleanField(default=False),
                ),
                (
                    "limited_usage_with_other_organizations",
                    models.BooleanField(default=False),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designs",
                        to="designs.collection",
                    ),
                ),
                (
                    "regular_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designs",
                        to="accounts.accountprofile",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designs",
                        to="organizations.workshop",
                    ),
                ),
            ],
            options={
                "db_table": "designs",
            },
        ),
        migrations.CreateModel(
            name="DesignerProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "designer_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("biography", models.TextField(blank=True, null=True)),
                ("social_media_website_links", models.JSONField(blank=True, null=True)),
                (
                    "designer_logo_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "designer_banner_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("tax_number", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("registration_date", models.DateField(blank=True, null=True)),
                (
                    "registration_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "registration_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "registration_certificate_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designer_profile",
                        to="accounts.accountprofile",
                    ),
                ),
            ],
            options={
                "db_table": "designer_profiles",
            },
        ),
        migrations.CreateModel(
            name="DesignPreview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_previews",
                        to="designs.design",
                    ),
                ),
            ],
            options={
                "db_table": "design_previews",
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "designer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="designs.designerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "stores",
            },
        ),
        migrations.AddField(
            model_name="design",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designs",
                to="designs.store",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="store",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection",
                to="designs.store",
            ),
        ),
        migrations.CreateModel(
            name="StoreProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("biography", models.TextField(blank=True, null=True)),
                (
                    "store_logo_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "store_banner_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_sponsored", models.BooleanField(default=False)),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storeprofile",
                        to="designs.store",
                    ),
                ),
            ],
            options={
                "db_table": "store_profiles",
            },
        ),
        migrations.AddField(
            model_name="design",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="design",
                to="designs.theme",
            ),
        ),
        migrations.CreateModel(
            name="DesignLike",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_likes",
                        to="accounts.accountprofile",
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_likes",
                        to="designs.design",
                    ),
                ),
            ],
            options={
                "db_table": "design_likes",
                "unique_together": {("design", "account_profile")},
            },
        ),
    ]
