# Generated by Django 5.0 on 2024-07-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="ai_generated",
            field=models.BooleanField(default=False),
        ),
    ]
