# Generated by Django 5.0 on 2024-06-13 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_roleaccount"),
        ("designs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="theme",
            old_name="logo_path",
            new_name="icon_path",
        ),
        migrations.RemoveField(
            model_name="store",
            name="account_profile",
        ),
        migrations.RemoveField(
            model_name="storeprofile",
            name="is_verified",
        ),
        migrations.CreateModel(
            name="DesignerProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("biography", models.TextField(blank=True, null=True)),
                (
                    "designer_profile_picture_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("social_media_links", models.JSONField(blank=True, null=True)),
                (
                    "designer_logo_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "designer_banner_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("designer_verified", models.BooleanField(default=False)),
                (
                    "designer_website",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tax_number", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("registration_date", models.DateField(blank=True, null=True)),
                (
                    "registration_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "registration_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "registration_certificate_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designer_profile",
                        to="accounts.accountprofile",
                    ),
                ),
            ],
            options={
                "db_table": "designer_profiles",
            },
        ),
        migrations.AddField(
            model_name="store",
            name="designer_profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stores",
                to="designs.designerprofile",
            ),
            preserve_default=False,
        ),
    ]
