# Generated by Django 5.0 on 2024-03-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("designs", "0001_initial"),
        ("personalizables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="personalizable_variants",
            field=models.ManyToManyField(
                related_name="designs", to="personalizables.personalizablevariant"
            ),
        ),
        migrations.AddField(
            model_name="designlike",
            name="account_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="design_likes",
                to="accounts.accountprofile",
            ),
        ),
        migrations.AddField(
            model_name="designlike",
            name="design",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="design_likes",
                to="designs.design",
            ),
        ),
        migrations.AddField(
            model_name="designpreview",
            name="design",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="design_previews",
                to="designs.design",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="account_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="store",
                to="accounts.accountprofile",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="store",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection",
                to="designs.store",
            ),
        ),
        migrations.AddField(
            model_name="storeprofile",
            name="store",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storeprofile",
                to="designs.store",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="design",
                to="designs.theme",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="designlike",
            unique_together={("design", "account_profile")},
        ),
    ]
