# Generated by Django 5.0 on 2024-05-21 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designs",
                to="designs.collection",
            ),
        ),
    ]
