# Generated by Django 5.0 on 2024-02-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="design",
            old_name="can_be_used_with_other_designs",
            new_name="exclusive",
        ),
        migrations.AddField(
            model_name="design",
            name="limited_personalizables",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="design",
            name="tags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name="collection",
            table="collections",
        ),
        migrations.AlterModelTable(
            name="design",
            table="designs",
        ),
        migrations.AlterModelTable(
            name="store",
            table="stores",
        ),
        migrations.AlterModelTable(
            name="storeprofile",
            table="store_profiles",
        ),
        migrations.AlterModelTable(
            name="theme",
            table="themes",
        ),
    ]
