# Generated by Django 5.0 on 2024-05-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_permission_role_permissions"),
        ("designs", "0002_initial"),
        ("organizations", "0002_alter_organizationmembership_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="design",
            old_name="price",
            new_name="base_price",
        ),
        migrations.RenameField(
            model_name="design",
            old_name="limited_personalizables",
            new_name="free",
        ),
        migrations.RemoveField(
            model_name="design",
            name="personalizable_variants",
        ),
        migrations.AddField(
            model_name="design",
            name="design_type",
            field=models.CharField(
                choices=[("3d", "3D"), ("2d", "2D")], default="2d", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="free_usage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="design",
            name="free_usage_with_designer_uploads",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="design",
            name="free_usage_with_other_organizations",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="design",
            name="free_usage_with_other_workshops",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="design",
            name="free_usage_with_same_collection",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="design",
            name="free_usage_with_same_organization",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="design",
            name="free_usage_with_same_workshop",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="design",
            name="free_usage_with_user_uploads",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="design",
            name="latest_publication_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="design",
            name="regular_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designs",
                to="accounts.accountprofile",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="sponsored",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="design",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designs",
                to="designs.store",
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="workshop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designs",
                to="organizations.workshop",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designs",
                to="designs.collection",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="exclusive_usage",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="design",
            name="to_be_published",
            field=models.BooleanField(default=False),
        ),
    ]
