# Generated by Django 5.0 on 2024-06-22 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0002_rename_logo_path_theme_icon_path_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="design",
            old_name="free",
            new_name="platform_specific",
        ),
        migrations.RenameField(
            model_name="designerprofile",
            old_name="designer_verified",
            new_name="is_verified",
        ),
        migrations.RenameField(
            model_name="designerprofile",
            old_name="designer_profile_picture_path",
            new_name="registration_address",
        ),
        migrations.RenameField(
            model_name="designerprofile",
            old_name="social_media_links",
            new_name="social_media_website_links",
        ),
        migrations.RemoveField(
            model_name="designerprofile",
            name="designer_website",
        ),
        migrations.RemoveField(
            model_name="designerprofile",
            name="registration_location",
        ),
    ]
