# Generated by Django 5.0 on 2024-05-23 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0002_alter_design_collection"),
    ]

    operations = [
        migrations.RenameField(
            model_name="design",
            old_name="free_usage_with_designer_uploads",
            new_name="limited_usage_with_designer_uploads",
        ),
        migrations.RenameField(
            model_name="design",
            old_name="free_usage_with_other_organizations",
            new_name="limited_usage_with_other_organizations",
        ),
        migrations.RenameField(
            model_name="design",
            old_name="free_usage_with_other_workshops",
            new_name="limited_usage_with_other_workshops",
        ),
        migrations.RenameField(
            model_name="design",
            old_name="free_usage_with_same_collection",
            new_name="limited_usage_with_same_collection",
        ),
        migrations.RenameField(
            model_name="design",
            old_name="free_usage_with_same_organization",
            new_name="limited_usage_with_same_organization",
        ),
        migrations.RenameField(
            model_name="design",
            old_name="free_usage_with_same_workshop",
            new_name="limited_usage_with_same_workshop",
        ),
        migrations.RenameField(
            model_name="design",
            old_name="free_usage_with_user_uploads",
            new_name="limited_usage_with_user_uploads",
        ),
    ]
