# Generated by Django 5.0 on 2024-02-27 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "designs",
            "0002_rename_can_be_used_with_other_designs_design_exclusive_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="theme",
            old_name="title",
            new_name="name",
        ),
    ]
