# Generated by Django 5.0 on 2024-03-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0002_design_price"),
        (
            "personalizables",
            "0003_alter_designedpersonalizablezone_designed_personalizable_variant",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="personalizable_variant",
            field=models.ManyToManyField(
                related_name="designs", to="personalizables.personalizablevariant"
            ),
        ),
    ]
