# Generated by Django 5.0 on 2024-06-24 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0003_rename_free_design_platform_specific_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="designerprofile",
            old_name="account",
            new_name="account_profile",
        ),
    ]
