# Generated by Django 5.0 on 2024-03-14 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0003_design_personalizable_variant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="design",
            old_name="personalizable_variant",
            new_name="personalizable_variants",
        ),
    ]
