# Generated by Django 5.0 on 2024-02-28 21:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_account_id_alter_accountprofile_id"),
        ("designs", "0003_rename_title_theme_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignLikes",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_likes",
                        to="accounts.accountprofile",
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_likes",
                        to="designs.design",
                    ),
                ),
            ],
            options={
                "db_table": "design_likes",
                "unique_together": {("design", "account_profile")},
            },
        ),
    ]
