# Generated by Django 5.0 on 2024-03-06 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0004_designlikes"),
        ("organizations", "0012_inventoryitem_currency_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="description",
        ),
        migrations.AddField(
            model_name="collection",
            name="workshop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection",
                to="organizations.workshop",
            ),
        ),
        migrations.CreateModel(
            name="DesignPreview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_previews",
                        to="designs.design",
                    ),
                ),
            ],
            options={
                "db_table": "design_previews",
            },
        ),
    ]
