# Generated by Django 5.0 on 2024-06-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_default_delivery_address_deliveryaddress_is_default"),
        ("designs", "0004_rename_account_designerprofile_account_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designerprofile",
            name="account_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designer_profile",
                to="accounts.accountprofile",
            ),
        ),
    ]
