# Generated by Django 5.0 on 2024-06-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0005_alter_designerprofile_account_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="designerprofile",
            name="designer_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
