# Generated by Django 5.0 on 2024-03-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0005_rename_title_collection_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="design",
            old_name="exclusive",
            new_name="exclusive_usage",
        ),
        migrations.AlterField(
            model_name="design",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
