# Generated by Django 5.0 on 2024-03-06 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0006_rename_exclusive_design_exclusive_usage_and_more"),
        ("organizations", "0012_inventoryitem_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="store",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection",
                to="designs.store",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="workshop",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection",
                to="organizations.workshop",
            ),
        ),
    ]
