# Generated by Django 5.0 on 2024-06-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0006_designerprofile_designer_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="theme",
            old_name="icon_path",
            new_name="icon_1_path",
        ),
        migrations.AddField(
            model_name="theme",
            name="icon_2_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="theme",
            name="icon_3_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
