# Generated by Django 5.0 on 2024-06-27 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "designs",
            "0007_rename_icon_path_theme_icon_1_path_theme_icon_2_path_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="design",
            name="platform_specific",
        ),
        migrations.AlterField(
            model_name="design",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="design",
                to="designs.theme",
            ),
        ),
    ]
