# Generated by Django 5.0 on 2024-03-06 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_remove_deliveryaddress_account_and_more"),
        ("designs", "0007_alter_collection_store_alter_collection_workshop"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DesignLikes",
            new_name="DesignLike",
        ),
    ]
