# Generated by Django 5.0 on 2024-07-10 18:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0008_remove_design_platform_specific_alter_design_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
