# Generated by Django 5.0 on 2024-03-06 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0008_rename_designlikes_designlike"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storeprofile",
            old_name="is_bestseller",
            new_name="is_sponsored",
        ),
        migrations.RemoveField(
            model_name="storeprofile",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="storeprofile",
            name="is_trending",
        ),
        migrations.RemoveField(
            model_name="storeprofile",
            name="is_upcoming",
        ),
    ]
