# Generated by Django 5.0 on 2024-03-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0009_rename_is_bestseller_storeprofile_is_sponsored_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storeprofile",
            old_name="is_sponsored",
            new_name="is_verified",
        ),
        migrations.AlterField(
            model_name="storeprofile",
            name="type",
            field=models.CharField(
                choices=[("personal", "Personal"), ("Sponsored", "Sponsored")],
                default="personal",
                max_length=255,
            ),
        ),
    ]
