# Generated by Django 5.0 on 2024-03-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0010_rename_is_sponsored_storeprofile_is_verified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeprofile",
            name="type",
        ),
        migrations.AddField(
            model_name="storeprofile",
            name="is_sponsored",
            field=models.BooleanField(default=False),
        ),
    ]
