# Generated by Django 5.0 on 2024-03-06 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0011_remove_storeprofile_type_storeprofile_is_sponsored"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeprofile",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storeprofile",
                to="designs.store",
            ),
        ),
    ]
