# Generated by Django 5.0 on 2024-03-06 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0012_alter_storeprofile_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeprofile",
            name="store",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storeprofile",
                to="designs.store",
            ),
        ),
    ]
