# Generated by Django 5.0 on 2024-03-07 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0013_alter_storeprofile_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
