# Generated by Django 5.0 on 2024-06-02 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("designs", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "departments",
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "options",
            },
        ),
        migrations.CreateModel(
            name="PersonalizationType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("logo_path", models.CharField(blank=True, max_length=255, null=True)),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "personalization_types",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
                ("logo_path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Unavailable", "Unavailable"),
                            ("Hidden", "Hidden"),
                            ("ComingSoon", "ComingSoon"),
                        ],
                        default="Available",
                        max_length=255,
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="personalizables.category",
                    ),
                ),
            ],
            options={
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="OptionValue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(max_length=255, null=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_values",
                        to="personalizables.option",
                    ),
                ),
            ],
            options={
                "db_table": "option_values",
            },
        ),
        migrations.CreateModel(
            name="Personalizable",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "brand",
                    models.CharField(
                        default="Generic Brand", max_length=255, null=True
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="Generic Model", max_length=255, null=True
                    ),
                ),
                ("is_open_for_personalization", models.BooleanField(default=False)),
                ("can_be_template", models.BooleanField(default=False)),
                ("used_with_specific_designs", models.BooleanField(default=False)),
                ("used_with_specific_workshops", models.BooleanField(default=False)),
                ("used_with_designers_designs", models.BooleanField(default=False)),
                (
                    "userd_with_user_uploaded_designs",
                    models.BooleanField(default=False),
                ),
                ("used_with_platform_designs", models.BooleanField(default=False)),
                (
                    "Department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department",
                        to="personalizables.department",
                    ),
                ),
                (
                    "allowed_designs",
                    models.ManyToManyField(
                        related_name="personalizables", to="designs.design"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="personalizables.category",
                    ),
                ),
            ],
            options={
                "db_table": "personalizables",
            },
        ),
        migrations.CreateModel(
            name="PersonalizableOption",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalizables",
                        to="personalizables.option",
                    ),
                ),
                (
                    "personalizable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="personalizables.personalizable",
                    ),
                ),
            ],
            options={
                "db_table": "personalizable_options",
            },
        ),
        migrations.CreateModel(
            name="PersonalizableVariant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.IntegerField(default=1, null=True)),
                (
                    "personalizable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="personalizables.personalizable",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalizable_variants",
                        to="organizations.inventoryitem",
                    ),
                ),
            ],
            options={
                "db_table": "personalizable_variants",
            },
        ),
        migrations.CreateModel(
            name="DesignedPersonalizableVariant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                (
                    "personalizable_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designed_personalizable_variant",
                        to="personalizables.personalizablevariant",
                    ),
                ),
            ],
            options={
                "db_table": "designed_personalizable_variants",
            },
        ),
        migrations.CreateModel(
            name="PersonalizableVariantValue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "option_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalizable_variants",
                        to="personalizables.optionvalue",
                    ),
                ),
                (
                    "personalizable_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalizable_variants",
                        to="personalizables.personalizableoption",
                    ),
                ),
                (
                    "personalizable_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_values",
                        to="personalizables.personalizablevariant",
                    ),
                ),
            ],
            options={
                "db_table": "personalizable_variant_values",
            },
        ),
        migrations.CreateModel(
            name="PersonalizableZone",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
                ("max_nb_designs", models.IntegerField(default=1, null=True)),
                ("x1", models.FloatField(null=True)),
                ("y1", models.FloatField(null=True)),
                ("x2", models.FloatField(null=True)),
                ("y2", models.FloatField(null=True)),
                (
                    "personalizable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="personalizables.personalizable",
                    ),
                ),
            ],
            options={
                "db_table": "personalizable_zones",
            },
        ),
        migrations.CreateModel(
            name="DesignedPersonalizableZone",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dx1", models.FloatField(null=True)),
                ("dy1", models.FloatField(null=True)),
                ("dx2", models.FloatField(null=True)),
                ("dy2", models.FloatField(null=True)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designed_personalizable_zone",
                        to="designs.design",
                    ),
                ),
                (
                    "designed_personalizable_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designed_personalizable_variant_zone",
                        to="personalizables.designedpersonalizablevariant",
                    ),
                ),
                (
                    "personalizable_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designed_personalizable_zone",
                        to="personalizables.personalizablezone",
                    ),
                ),
            ],
            options={
                "db_table": "designed_personalizable_zones",
            },
        ),
        migrations.CreateModel(
            name="PersonalizationMethod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("logo_path", models.CharField(blank=True, max_length=255, null=True)),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "personalization_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalization_method",
                        to="personalizables.personalizationtype",
                    ),
                ),
            ],
            options={
                "db_table": "personalization_methods",
            },
        ),
    ]
