# Generated by Django 5.0 on 2024-07-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="designedpersonalizablezonedesign",
            name="d",
            field=models.FloatField(null=True),
        ),
    ]
