# Generated by Django 5.0 on 2024-02-23 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_alter_inventory_id_alter_inventoryitem_id_and_more"),
        ("personalizables", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="personalizablevariant",
            name="color",
        ),
        migrations.RemoveField(
            model_name="personalizablevariant",
            name="material",
        ),
        migrations.RemoveField(
            model_name="personalizablevariant",
            name="size",
        ),
        migrations.RemoveField(
            model_name="personalizable",
            name="availability",
        ),
        migrations.RemoveField(
            model_name="personalizablevariant",
            name="stock_quantity",
        ),
        migrations.AddField(
            model_name="personalizable",
            name="image_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalizablevariant",
            name="brand",
            field=models.CharField(default="Generic Brand", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalizablevariant",
            name="model",
            field=models.CharField(default="Generic Model", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalizablevariant",
            name="sku",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personalizable_variants",
                to="organizations.inventoryitem",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="AllowedVariantPersonalizationMethod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "personalizable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_personalizables",
                        to="personalizables.personalizable",
                    ),
                ),
                (
                    "personalization_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_personalizables",
                        to="personalizables.personalizationmethod",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OptionValue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_values",
                        to="personalizables.option",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonalizableOption",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalizables",
                        to="personalizables.option",
                    ),
                ),
                (
                    "personalizable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="personalizables.personalizable",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonalizableVariantValue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "option_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalizable_variants",
                        to="personalizables.optionvalue",
                    ),
                ),
                (
                    "personalizable_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalizable_variants",
                        to="personalizables.personalizableoption",
                    ),
                ),
                (
                    "personalizable_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_values",
                        to="personalizables.personalizablevariant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="AllowedPersonalizablesPersonalization",
        ),
        migrations.DeleteModel(
            name="Color",
        ),
        migrations.DeleteModel(
            name="Material",
        ),
        migrations.DeleteModel(
            name="Size",
        ),
    ]
