# Generated by Django 5.0 on 2024-03-09 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0001_initial"),
        ("products", "0005_bulkpurchasepromotion_firsttimepurchasepromotion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="designedpersonalizablevariant",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_designed_personalizable_variant",
                to="products.product",
            ),
            preserve_default=False,
        ),
    ]
