# Generated by Django 5.0 on 2024-06-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="image_path",
            new_name="image_path_1",
        ),
        migrations.RenameField(
            model_name="personalizable",
            old_name="used_with_specific_designs",
            new_name="used_with_other_workshops_designs",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image_path",
        ),
        migrations.RemoveField(
            model_name="category",
            name="logo_path",
        ),
        migrations.RemoveField(
            model_name="personalizable",
            name="used_with_specific_workshops",
        ),
        migrations.RemoveField(
            model_name="personalizablevariant",
            name="sku",
        ),
        migrations.AddField(
            model_name="department",
            name="image_path_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="image_path_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
