# Generated by Django 5.0 on 2024-07-19 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0001_initial"),
        ("personalizables", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designedzonerelateddesign",
            name="design",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designed_zones",
                to="designs.design",
            ),
        ),
        migrations.AlterField(
            model_name="designedzonerelateddesign",
            name="designed_personalizable_zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_designs",
                to="personalizables.designedpersonalizablezone",
            ),
        ),
    ]
