# Generated by Django 5.0 on 2024-07-15 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0001_initial"),
        ("personalizables", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dummymodel",
            name="name",
        ),
        migrations.AddField(
            model_name="dummymodel",
            name="design",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bbbb",
                to="designs.design",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dummymodel",
            name="designed_personalizable_zone",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rrrr",
                to="personalizables.designedpersonalizablezone",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dummymodel",
            name="dx1",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="dummymodel",
            name="dx2",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="dummymodel",
            name="dy1",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="dummymodel",
            name="dy2",
            field=models.FloatField(null=True),
        ),
    ]
