# Generated by Django 5.0 on 2024-02-26 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="designedpersonalizablevariant",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="personalization_method",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="personalizables.personalizationmethod",
            ),
            preserve_default=False,
        ),
    ]
