# Generated by Django 5.0 on 2024-07-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="designedpersonalizablezonedesign",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="designedpersonalizablezonedesign",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
