# Generated by Django 5.0 on 2024-07-15 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0001_initial"),
        ("personalizables", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DesignedPersonalizableZoneRelatedDesign",
            new_name="ZoneRelatedDesign",
        ),
        migrations.AlterModelTable(
            name="zonerelateddesign",
            table="zone_related_designs",
        ),
    ]
