# Generated by Django 5.0 on 2024-07-15 19:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "dummy_model",
            },
        ),
    ]
