# Generated by Django 5.0 on 2024-05-17 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0003_rename_price_design_base_price_and_more"),
        ("personalizables", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "departments",
            },
        ),
        migrations.RemoveField(
            model_name="designedpersonalizablevariant",
            name="product",
        ),
        migrations.RemoveField(
            model_name="personalizable",
            name="image_path",
        ),
        migrations.AddField(
            model_name="personalizable",
            name="designs",
            field=models.ManyToManyField(
                related_name="personalizables", to="designs.design"
            ),
        ),
        migrations.AddField(
            model_name="personalizable",
            name="is_limited_specific",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personalizable",
            name="is_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personalizablevariant",
            name="quantity",
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name="personalizable",
            name="Department",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department",
                to="personalizables.department",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="AllowedVariantPersonalizationMethod",
        ),
    ]
