# Generated by Django 5.0 on 2024-07-15 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0001_initial"),
        ("personalizables", "0002_designedpersonalizablezonedesign_d"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignedPersonalizableZoneRelatedDesign",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dx1", models.FloatField(null=True)),
                ("dy1", models.FloatField(null=True)),
                ("dx2", models.FloatField(null=True)),
                ("dy2", models.FloatField(null=True)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designed_personalizable_zone",
                        to="designs.design",
                    ),
                ),
                (
                    "designed_personalizable_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designs",
                        to="personalizables.designedpersonalizablezone",
                    ),
                ),
            ],
            options={
                "db_table": "designed_personalizable_zone_related_designs",
            },
        ),
        migrations.DeleteModel(
            name="DesignedPersonalizableZoneDesign",
        ),
    ]
