# Generated by Django 5.0 on 2024-03-09 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0002_designedpersonalizablevariant_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designedpersonalizablezone",
            name="designed_personalizable_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designed_personalizable_variant_zone",
                to="personalizables.designedpersonalizablevariant",
            ),
        ),
    ]
