# Generated by Django 5.0 on 2024-07-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0002_dummymodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="dummymodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dummymodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
