# Generated by Django 5.0 on 2024-07-15 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0001_initial"),
        ("personalizables", "0002_remove_dummymodel_name_dummymodel_design_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DummyModel",
            new_name="DesignedZoneRelatedDesign",
        ),
    ]
