# Generated by Django 5.0 on 2024-07-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0002_rename_image_path_department_image_path_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalizable",
            old_name="userd_with_user_uploaded_designs",
            new_name="used_with_user_uploaded_designs",
        ),
        migrations.RenameField(
            model_name="personalizationtype",
            old_name="image_path",
            new_name="image_path_1",
        ),
        migrations.RenameField(
            model_name="personalizationtype",
            old_name="logo_path",
            new_name="image_path_2",
        ),
        migrations.AddField(
            model_name="category",
            name="image_path_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="image_path_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="image_path_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalizablevariant",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalizationtype",
            name="image_path_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
