# Generated by Django 5.0 on 2024-02-24 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0002_option_remove_personalizablevariant_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="depth",
        ),
        migrations.RemoveField(
            model_name="category",
            name="numchild",
        ),
        migrations.RemoveField(
            model_name="category",
            name="path",
        ),
    ]
