# Generated by Django 5.0 on 2024-02-27 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0002_designedpersonalizablevariant_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="optionvalue",
            old_name="name",
            new_name="value",
        ),
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="option",
            name="description",
        ),
        migrations.RemoveField(
            model_name="optionvalue",
            name="description",
        ),
        migrations.AlterModelTable(
            name="allowedvariantpersonalizationmethod",
            table="AllowedVariantPersonalizationMethods",
        ),
        migrations.AlterModelTable(
            name="category",
            table="Categories",
        ),
        migrations.AlterModelTable(
            name="designedpersonalizablevariant",
            table="DesignedPersonalizableVariants",
        ),
        migrations.AlterModelTable(
            name="designedpersonalizablezone",
            table="DesignedPersonalizableZones",
        ),
        migrations.AlterModelTable(
            name="option",
            table="Options",
        ),
        migrations.AlterModelTable(
            name="optionvalue",
            table="OptionValues",
        ),
        migrations.AlterModelTable(
            name="personalizable",
            table="Personalizables",
        ),
        migrations.AlterModelTable(
            name="personalizableoption",
            table="PersonalizableOptions",
        ),
        migrations.AlterModelTable(
            name="personalizablevariant",
            table="PersonalizableVariants",
        ),
        migrations.AlterModelTable(
            name="personalizablevariantvalue",
            table="PersonalizableVariantValues",
        ),
        migrations.AlterModelTable(
            name="personalizablezone",
            table="PersonalizableZones",
        ),
        migrations.AlterModelTable(
            name="personalizationmethod",
            table="PersonalizationMethods",
        ),
        migrations.AlterModelTable(
            name="personalizationtype",
            table="PersonalizationTypes",
        ),
        migrations.AlterModelTable(
            name="product",
            table="Products",
        ),
        migrations.CreateModel(
            name="DesignedPersonalizableVariantPreview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "designed_personalizable_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designed_personalizable_variant_preview",
                        to="personalizables.designedpersonalizablevariant",
                    ),
                ),
            ],
            options={
                "db_table": "DesignedPersonalizableVariantPreviews",
            },
        ),
    ]
