# Generated by Django 5.0 on 2024-07-15 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0003_rename_dummymodel_designedzonerelateddesign"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="designedzonerelateddesign",
            table="designed_zone_related_designs",
        ),
    ]
