# Generated by Django 5.0 on 2024-05-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0003_department_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalizable",
            old_name="is_limited_specific",
            new_name="can_be_template",
        ),
        migrations.RenameField(
            model_name="personalizable",
            old_name="is_open",
            new_name="is_open_for_personalization",
        ),
        migrations.AddField(
            model_name="personalizable",
            name="used_with_designers_designs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personalizable",
            name="used_with_platform_designs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personalizable",
            name="used_with_specific_designs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personalizable",
            name="used_with_specific_workshops",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personalizable",
            name="userd_with_user_uploaded_designs",
            field=models.BooleanField(default=False),
        ),
    ]
