# Generated by Django 5.0 on 2024-07-21 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0003_alter_designedpersonalizablevariant_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designedpersonalizablezone",
            name="designed_personalizable_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designed_personalizable_variant_zones",
                to="personalizables.designedpersonalizablevariant",
            ),
        ),
    ]
