# Generated by Django 5.0 on 2024-07-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "personalizables",
            "0003_rename_userd_with_user_uploaded_designs_personalizable_used_with_user_uploaded_designs_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalizationmethod",
            old_name="image_path",
            new_name="image_path_1",
        ),
        migrations.RenameField(
            model_name="personalizationmethod",
            old_name="logo_path",
            new_name="image_path_2",
        ),
        migrations.AddField(
            model_name="personalizationmethod",
            name="image_path_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
