# Generated by Django 5.0 on 2024-07-15 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0003_dummymodel_created_at_dummymodel_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zonerelateddesign",
            name="designed_personalizable_zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_designs",
                to="personalizables.designedpersonalizablezone",
            ),
        ),
    ]
