# Generated by Django 5.0 on 2024-02-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0003_rename_name_optionvalue_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Unavailable", "Unavailable"),
                    ("Hidden", "Hidden"),
                    ("ComingSoon", "ComingSoon"),
                ],
                default="Available",
                max_length=255,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="allowedvariantpersonalizationmethod",
            unique_together={("personalizable", "personalization_method")},
        ),
    ]
