# Generated by Django 5.0 on 2024-02-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "personalizables",
            "0003_remove_category_depth_remove_category_numchild_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalizablevariant",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="personalizablevariant",
            name="model",
        ),
        migrations.AddField(
            model_name="personalizable",
            name="brand",
            field=models.CharField(default="Generic Brand", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personalizable",
            name="model",
            field=models.CharField(default="Generic Model", max_length=255, null=True),
        ),
    ]
