# Generated by Django 4.0.10 on 2023-09-10 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalizables', '0004_rename_fixed_choices_size_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizablevariant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_of_a_color', to='personalizables.color'),
        ),
        migrations.AlterField(
            model_name='personalizablevariant',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_of_a_material', to='personalizables.material'),
        ),
        migrations.AlterField(
            model_name='personalizablevariant',
            name='personalizable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='personalizables.personalizable'),
        ),
        migrations.AlterField(
            model_name='personalizablevariant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_of_a_size', to='personalizables.size'),
        ),
    ]
