# Generated by Django 5.0 on 2024-07-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "personalizables",
            "0004_rename_image_path_personalizationmethod_image_path_1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
