# Generated by Django 5.0 on 2024-07-15 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0001_initial"),
        (
            "personalizables",
            "0004_alter_zonerelateddesign_designed_personalizable_zone",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="zonerelateddesign",
            name="design",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designed_zones",
                to="designs.design",
            ),
        ),
    ]
