# Generated by Django 5.0 on 2024-02-27 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0004_alter_category_availability_status_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="allowedvariantpersonalizationmethod",
            table="allowed_variant_personalization_methods",
        ),
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
        migrations.AlterModelTable(
            name="designedpersonalizablevariant",
            table="designed_personalizable_variants",
        ),
        migrations.AlterModelTable(
            name="designedpersonalizablevariantpreview",
            table="designed_personalizable_variant_previews",
        ),
        migrations.AlterModelTable(
            name="designedpersonalizablezone",
            table="designed_personalizable_zones",
        ),
        migrations.AlterModelTable(
            name="option",
            table="options",
        ),
        migrations.AlterModelTable(
            name="optionvalue",
            table="option_values",
        ),
        migrations.AlterModelTable(
            name="personalizable",
            table="personalizables",
        ),
        migrations.AlterModelTable(
            name="personalizableoption",
            table="personalizable_options",
        ),
        migrations.AlterModelTable(
            name="personalizablevariantvalue",
            table="personalizable_variant_values",
        ),
        migrations.AlterModelTable(
            name="personalizablezone",
            table="personalizable_zones",
        ),
        migrations.AlterModelTable(
            name="personalizationmethod",
            table="personalization_methods",
        ),
        migrations.AlterModelTable(
            name="personalizationtype",
            table="personalization_types",
        ),
        migrations.AlterModelTable(
            name="product",
            table="products",
        ),
    ]
