# Generated by Django 5.0 on 2024-07-21 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "personalizables",
            "0004_alter_designedpersonalizablezone_designed_personalizable_variant",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="optionvalue",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="personalizable",
            name="brand",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="Generic Brand",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalizable",
            name="model",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="Generic Model",
                max_length=255,
                null=True,
            ),
        ),
    ]
