# Generated by Django 5.0 on 2024-02-28 21:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "personalizables",
            "0005_alter_allowedvariantpersonalizationmethod_table_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="designedpersonalizablezone",
            old_name="dh",
            new_name="dx1",
        ),
        migrations.RenameField(
            model_name="designedpersonalizablezone",
            old_name="dw",
            new_name="dx2",
        ),
        migrations.RenameField(
            model_name="designedpersonalizablezone",
            old_name="dx",
            new_name="dy1",
        ),
        migrations.RenameField(
            model_name="designedpersonalizablezone",
            old_name="dy",
            new_name="dy2",
        ),
        migrations.RemoveField(
            model_name="personalizablezone",
            name="dh",
        ),
        migrations.RemoveField(
            model_name="personalizablezone",
            name="dw",
        ),
        migrations.RemoveField(
            model_name="personalizablezone",
            name="dx",
        ),
        migrations.RemoveField(
            model_name="personalizablezone",
            name="dy",
        ),
    ]
