# Generated by Django 5.0 on 2024-07-21 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0005_alter_option_id_alter_optionvalue_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalizablevariantvalue",
            name="option_value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_variant_values",
                to="personalizables.optionvalue",
            ),
        ),
        migrations.AlterField(
            model_name="personalizablevariantvalue",
            name="personalizable_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personalizable_option_variant_values",
                to="personalizables.personalizableoption",
            ),
        ),
        migrations.AlterField(
            model_name="personalizablevariantvalue",
            name="personalizable_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personalizable_variant_values",
                to="personalizables.personalizablevariant",
            ),
        ),
    ]
