# Generated by Django 5.0 on 2024-07-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0005_category_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalizable",
            old_name="Department",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="personalizable",
            old_name="used_with_designers_designs",
            new_name="used_with_same_workshop_designs",
        ),
        migrations.AddField(
            model_name="personalizable",
            name="used_with_store_designs",
            field=models.BooleanField(default=False),
        ),
    ]
