# Generated by Django 5.0 on 2024-07-03 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "personalizables",
            "0006_rename_department_personalizable_department_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalizable",
            old_name="used_with_other_workshops_designs",
            new_name="used_with_other_workshop_designs",
        ),
    ]
