# Generated by Django 5.0 on 2024-02-28 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0006_rename_dh_designedpersonalizablezone_dx1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalizablezone",
            old_name="maximum_number_of_designs",
            new_name="max_nb_designs",
        ),
        migrations.RemoveField(
            model_name="personalizablezone",
            name="default_display",
        ),
    ]
