# Generated by Django 5.0 on 2024-07-10 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designs", "0009_alter_collection_id_alter_design_id_alter_store_id"),
        (
            "personalizables",
            "0007_rename_used_with_other_workshops_designs_personalizable_used_with_other_workshop_designs",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designedpersonalizablezone",
            name="design",
        ),
        migrations.RemoveField(
            model_name="designedpersonalizablezone",
            name="dx1",
        ),
        migrations.RemoveField(
            model_name="designedpersonalizablezone",
            name="dx2",
        ),
        migrations.RemoveField(
            model_name="designedpersonalizablezone",
            name="dy1",
        ),
        migrations.RemoveField(
            model_name="designedpersonalizablezone",
            name="dy2",
        ),
        migrations.AddField(
            model_name="designedpersonalizablezone",
            name="components",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DesignedPersonalizableZoneDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dx", models.FloatField(null=True)),
                ("dy", models.FloatField(null=True)),
                ("dh", models.FloatField(null=True)),
                ("dw", models.FloatField(null=True)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designed_personalizable_zone",
                        to="designs.design",
                    ),
                ),
                (
                    "designed_personalizable_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designs",
                        to="personalizables.designedpersonalizablezone",
                    ),
                ),
            ],
            options={
                "db_table": "designed_personalizable_zone_designs",
            },
        ),
    ]
