# Generated by Django 5.0 on 2024-02-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "personalizables",
            "0007_rename_maximum_number_of_designs_personalizablezone_max_nb_designs_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalizablezone",
            name="max_nb_designs",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
