# Generated by Django 5.0 on 2024-07-11 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_workshop_is_sponsored"),
        ("personalizables", "0008_remove_designedpersonalizablezone_design_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalizable",
            name="workshop",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personalizables",
                to="organizations.workshop",
            ),
            preserve_default=False,
        ),
    ]
