# Generated by Django 5.0 on 2024-03-04 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0008_alter_personalizablezone_max_nb_designs"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="personalizablevariant",
            table="personalizable_variants",
        ),
    ]
