# Generated by Django 5.0 on 2024-07-13 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0009_personalizable_workshop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalizablevariantvalue",
            name="option_value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_values",
                to="personalizables.optionvalue",
            ),
        ),
        migrations.AlterField(
            model_name="personalizablevariantvalue",
            name="personalizable_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_values",
                to="personalizables.personalizableoption",
            ),
        ),
        migrations.AlterField(
            model_name="personalizablevariantvalue",
            name="personalizable_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_values",
                to="personalizables.personalizablevariant",
            ),
        ),
    ]
