# Generated by Django 5.0 on 2024-03-06 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0009_alter_personalizablevariant_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPreview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_previews",
                        to="personalizables.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_previews",
            },
        ),
    ]
