# Generated by Django 5.0 on 2024-03-07 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0010_productpreview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="designed_personalizable_variant",
        ),
        migrations.RemoveField(
            model_name="product",
            name="personalization_method",
        ),
        migrations.RemoveField(
            model_name="productpreview",
            name="product",
        ),
        migrations.DeleteModel(
            name="DesignedPersonalizableVariantPreview",
        ),
    ]
