# Generated by Django 5.0 on 2024-07-13 22:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "personalizables",
            "0010_alter_personalizablevariantvalue_option_value_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalizablevariant",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
