# Generated by Django 5.0 on 2024-07-13 22:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0011_alter_personalizablevariant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalizablevariantvalue",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
