# Generated by Django 5.0 on 2024-03-07 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_cartitem_product_alter_orderitem_product"),
        ("personalizables", "0011_remove_product_category_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductPreview",
        ),
    ]
