# Generated by Django 5.0 on 2024-07-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0012_alter_personalizablevariantvalue_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalizablevariant",
            name="base_price",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
