# Generated by Django 5.0 on 2024-07-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0013_personalizablevariant_base_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalizable",
            name="is_sponsored",
            field=models.BooleanField(default=False),
        ),
    ]
