# Generated by Django 5.0 on 2024-07-15 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0014_personalizable_is_sponsored"),
    ]

    operations = [
        migrations.RenameField(
            model_name="designedpersonalizablezonedesign",
            old_name="dh",
            new_name="dx1",
        ),
        migrations.RenameField(
            model_name="designedpersonalizablezonedesign",
            old_name="dw",
            new_name="dx2",
        ),
        migrations.RenameField(
            model_name="designedpersonalizablezonedesign",
            old_name="dx",
            new_name="dy1",
        ),
        migrations.RenameField(
            model_name="designedpersonalizablezonedesign",
            old_name="dy",
            new_name="dy2",
        ),
        migrations.AlterField(
            model_name="designedpersonalizablezonedesign",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
