# Generated by Django 5.0 on 2024-07-15 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalizables", "0014_personalizable_is_sponsored"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designedpersonalizablezonedesign",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
