# Generated by Django 4.0.10 on 2023-09-04 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalizables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizable',
            name='image_path',
        ),
        migrations.AlterField(
            model_name='personalizablevariant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='personalizables.color'),
        ),
        migrations.AlterField(
            model_name='personalizablevariant',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='personalizables.material'),
        ),
        migrations.AlterField(
            model_name='personalizablevariant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='personalizables.size'),
        ),
    ]
