# Generated by Django 4.0.10 on 2023-09-10 11:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_remove_designedpersonalizable_personalizable_variant_and_more'),
        ('personalizables', '0002_remove_personalizable_image_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignedPersonalizableVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='personalizablevariant',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='allowedpersonalizablespersonalization',
            name='personalizable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_personalizables', to='personalizables.personalizable'),
        ),
        migrations.AlterField(
            model_name='allowedpersonalizablespersonalization',
            name='personalization_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_personalization_types', to='personalizables.personalizationtype'),
        ),
        migrations.CreateModel(
            name='DesignedPersonalizableZone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dx', models.FloatField(null=True)),
                ('dy', models.FloatField(null=True)),
                ('dh', models.FloatField(null=True)),
                ('dw', models.FloatField(null=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designed_personalizable_zone', to='designs.design')),
                ('designed_personalizable_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designed_personalizable_zone', to='personalizables.designedpersonalizablevariant')),
                ('personalizable_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designed_personalizable_zone', to='personalizables.personalizablezone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='designedpersonalizablevariant',
            name='personalizable_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designed_personalizable_variant', to='personalizables.personalizablevariant'),
        ),
    ]
