# Generated by Django 4.0.10 on 2023-09-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizables', '0003_designedpersonalizablevariant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='fixed_choices',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='personalizablevariant',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='personalizablevariant',
            name='stock_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
