# Generated by Django 4.0.10 on 2023-09-04 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='store', to='usermanagement.userprofile'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
