# Generated by Django 4.0.10 on 2023-09-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_alter_store_user_profile_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designedpersonalizable',
            name='personalizable_variant',
        ),
        migrations.RemoveField(
            model_name='designedpersonalizablezone',
            name='design',
        ),
        migrations.RemoveField(
            model_name='designedpersonalizablezone',
            name='designed_personalizable',
        ),
        migrations.RemoveField(
            model_name='designedpersonalizablezone',
            name='personalizable_zone',
        ),
    ]
