# Generated by Django 4.0.10 on 2023-09-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_remove_designedpersonalizable_personalizable_variant_and_more'),
        ('products', '0002_remove_product_designed_personalizable_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesignedPersonalizable',
        ),
        migrations.DeleteModel(
            name='DesignedPersonalizableZone',
        ),
    ]
